/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './api/ability-api';
export * from './api/berry-api';
export * from './api/berry-firmness-api';
export * from './api/berry-flavor-api';
export * from './api/characteristic-api';
export * from './api/contest-effect-api';
export * from './api/contest-type-api';
export * from './api/egg-group-api';
export * from './api/encounter-condition-api';
export * from './api/encounter-condition-value-api';
export * from './api/encounter-method-api';
export * from './api/evolution-chain-api';
export * from './api/evolution-trigger-api';
export * from './api/gender-api';
export * from './api/generation-api';
export * from './api/growth-rate-api';
export * from './api/item-api';
export * from './api/item-attribute-api';
export * from './api/item-category-api';
export * from './api/item-fling-effect-api';
export * from './api/item-pocket-api';
export * from './api/language-api';
export * from './api/location-api';
export * from './api/location-area-api';
export * from './api/machine-api';
export * from './api/move-api';
export * from './api/move-ailment-api';
export * from './api/move-battle-style-api';
export * from './api/move-category-api';
export * from './api/move-damage-class-api';
export * from './api/move-learn-method-api';
export * from './api/move-target-api';
export * from './api/nature-api';
export * from './api/pal-park-area-api';
export * from './api/pokeathlon-stat-api';
export * from './api/pokedex-api';
export * from './api/pokemon-api';
export * from './api/pokemon-color-api';
export * from './api/pokemon-form-api';
export * from './api/pokemon-habitat-api';
export * from './api/pokemon-shape-api';
export * from './api/pokemon-species-api';
export * from './api/region-api';
export * from './api/stat-api';
export * from './api/super-contest-effect-api';
export * from './api/type-api';
export * from './api/version-api';
export * from './api/version-group-api';

