/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Ability } from './ability';

/**
 * 
 * @export
 * @interface AbilityList200Response
 */
export interface AbilityList200Response {
    /**
     * The total number of abilities available
     * @type {number}
     * @memberof AbilityList200Response
     */
    'count'?: number;
    /**
     * The URL for the next page of abilities (null if none)
     * @type {string}
     * @memberof AbilityList200Response
     */
    'next'?: string;
    /**
     * The URL for the previous page of abilities (null if none)
     * @type {string}
     * @memberof AbilityList200Response
     */
    'previous'?: string;
    /**
     * 
     * @type {Array<Ability>}
     * @memberof AbilityList200Response
     */
    'results'?: Array<Ability>;
}

