/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Effect } from './effect';
// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * 
 * @export
 * @interface AbilityEffectChange
 */
export interface AbilityEffectChange {
    /**
     * 
     * @type {Array<Effect>}
     * @memberof AbilityEffectChange
     */
    'effect_entries': Array<Effect>;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof AbilityEffectChange
     */
    'version_group': NamedAPIResource;
}

