/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbilityGeneration } from './ability-generation';
// May contain unused imports in some cases
// @ts-ignore
import { AbilityNamesInner } from './ability-names-inner';

/**
 * 
 * @export
 * @interface Ability
 */
export interface Ability {
    /**
     * The identifier for this ability resource.
     * @type {number}
     * @memberof Ability
     */
    'id'?: number;
    /**
     * The name for this ability resource.
     * @type {string}
     * @memberof Ability
     */
    'name'?: string;
    /**
     * Whether or not this ability originated in the main series of the video games.
     * @type {boolean}
     * @memberof Ability
     */
    'is_main_series'?: boolean;
    /**
     * 
     * @type {AbilityGeneration}
     * @memberof Ability
     */
    'generation'?: AbilityGeneration;
    /**
     * 
     * @type {Array<AbilityNamesInner>}
     * @memberof Ability
     */
    'names'?: Array<AbilityNamesInner>;
}

