/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AbilityNamesInnerLanguage
 */
export interface AbilityNamesInnerLanguage {
    /**
     * The name of the language.
     * @type {string}
     * @memberof AbilityNamesInnerLanguage
     */
    'name'?: string;
    /**
     * The URL of the API endpoint for the language.
     * @type {string}
     * @memberof AbilityNamesInnerLanguage
     */
    'url'?: string;
}

