/* tslint:disable */
/* eslint-disable */
/**
 * KG Pokemon API
 * Pokemon API for Konrad developer onboarding.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A badge that trainers can earn
 * @export
 * @interface Badge
 */
export interface Badge {
    /**
     * 
     * @type {number}
     * @memberof Badge
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Badge
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Badge
     */
    'giver'?: string;
    /**
     * 
     * @type {string}
     * @memberof Badge
     */
    'gym'?: string;
    /**
     * 
     * @type {string}
     * @memberof Badge
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof Badge
     */
    'image'?: string;
}

