/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BerryFirmness } from './berry-firmness';
// May contain unused imports in some cases
// @ts-ignore
import { BerryFlavorMap } from './berry-flavor-map';

/**
 * 
 * @export
 * @interface Berry
 */
export interface Berry {
    /**
     * The identifier for this berry resource
     * @type {number}
     * @memberof Berry
     */
    'id': number;
    /**
     * The name for this berry resource
     * @type {string}
     * @memberof Berry
     */
    'name': string;
    /**
     * Time it takes the tree to grow one stage, in hours. Berry trees go through four of these growth stages before they can be picked.
     * @type {number}
     * @memberof Berry
     */
    'growth_time': number;
    /**
     * The maximum number of these berries that can grow on one tree in Generation IV
     * @type {number}
     * @memberof Berry
     */
    'max_harvest': number;
    /**
     * The power of the move \"Natural Gift\" when used with this Berry
     * @type {number}
     * @memberof Berry
     */
    'natural_gift_power': number;
    /**
     * The size of this Berry, in millimeters
     * @type {number}
     * @memberof Berry
     */
    'size': number;
    /**
     * The smoothness of this Berry, used in making Pokéblocks or Poffins
     * @type {number}
     * @memberof Berry
     */
    'smoothness': number;
    /**
     * The speed at which this Berry dries out the soil as it grows. A higher rate means the soil dries more quickly.
     * @type {number}
     * @memberof Berry
     */
    'soil_dryness': number;
    /**
     * 
     * @type {BerryFirmness}
     * @memberof Berry
     */
    'firmness': BerryFirmness;
    /**
     * A list of references to each flavor a berry can have and the potency of each of those flavors in regard to this berry.
     * @type {Array<BerryFlavorMap>}
     * @memberof Berry
     */
    'flavors': Array<BerryFlavorMap>;
}

