/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BerryFirmness } from './berry-firmness';

/**
 * 
 * @export
 * @interface BerryFirmnessList200Response
 */
export interface BerryFirmnessList200Response {
    /**
     * The total number of berry firmnesses available from this API.
     * @type {number}
     * @memberof BerryFirmnessList200Response
     */
    'count'?: number;
    /**
     * The URL for the next page of results, or null if there are no more results.
     * @type {string}
     * @memberof BerryFirmnessList200Response
     */
    'next'?: string | null;
    /**
     * The URL for the previous page of results, or null if this is the first page.
     * @type {string}
     * @memberof BerryFirmnessList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<BerryFirmness>}
     * @memberof BerryFirmnessList200Response
     */
    'results'?: Array<BerryFirmness>;
}

