/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BerryFlavor } from './berry-flavor';

/**
 * 
 * @export
 * @interface BerryFlavorMap
 */
export interface BerryFlavorMap {
    /**
     * How powerful the referenced flavor is for this berry
     * @type {number}
     * @memberof BerryFlavorMap
     */
    'potency': number;
    /**
     * 
     * @type {BerryFlavor}
     * @memberof BerryFlavorMap
     */
    'flavor': BerryFlavor;
}

