/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FlavorText } from './flavor-text';
// May contain unused imports in some cases
// @ts-ignore
import { VerboseEffect } from './verbose-effect';

/**
 * 
 * @export
 * @interface ContestEffect
 */
export interface ContestEffect {
    /**
     * The identifier for this contest effect resource
     * @type {number}
     * @memberof ContestEffect
     */
    'id': number;
    /**
     * The base number of hearts the user of this move gets
     * @type {number}
     * @memberof ContestEffect
     */
    'appeal': number;
    /**
     * The base number of hearts the user\'s opponent loses
     * @type {number}
     * @memberof ContestEffect
     */
    'jam': number;
    /**
     * The flavor text of this contest effect listed in different languages
     * @type {Array<VerboseEffect>}
     * @memberof ContestEffect
     */
    'effect_entries': Array<VerboseEffect>;
    /**
     * The flavor text of this contest effect listed in different languages
     * @type {Array<FlavorText>}
     * @memberof ContestEffect
     */
    'flavor_text_entries': Array<FlavorText>;
}

