/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbilityEffectChange } from './ability-effect-change';
// May contain unused imports in some cases
// @ts-ignore
import { ContestComboSets } from './contest-combo-sets';
// May contain unused imports in some cases
// @ts-ignore
import { ContestType } from './contest-type';
// May contain unused imports in some cases
// @ts-ignore
import { EffectEffect } from './effect-effect';
// May contain unused imports in some cases
// @ts-ignore
import { FlavorText } from './flavor-text';
// May contain unused imports in some cases
// @ts-ignore
import { Generation } from './generation';
// May contain unused imports in some cases
// @ts-ignore
import { MachineVersionDetail } from './machine-version-detail';
// May contain unused imports in some cases
// @ts-ignore
import { MoveMetaData } from './move-meta-data';
// May contain unused imports in some cases
// @ts-ignore
import { MoveStatChange } from './move-stat-change';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonSpecies } from './pokemon-species';
// May contain unused imports in some cases
// @ts-ignore
import { SuperContestEffect } from './super-contest-effect';

/**
 * An effect that occurs in a game, e.g. causing a Pokémon to fall asleep.
 * @export
 * @interface Effect
 */
export interface Effect {
    /**
     * The identifier for this effect resource
     * @type {number}
     * @memberof Effect
     */
    'id'?: number;
    /**
     * The name for this effect resource
     * @type {string}
     * @memberof Effect
     */
    'name'?: string;
    /**
     * The list of effect text entries
     * @type {Array<EffectEffect>}
     * @memberof Effect
     */
    'effect_entries'?: Array<EffectEffect>;
    /**
     * The flavor text entries that describe this effect
     * @type {Array<EffectEffect>}
     * @memberof Effect
     */
    'pokemon_flavor_text_entries'?: Array<EffectEffect>;
    /**
     * 
     * @type {PokemonSpecies}
     * @memberof Effect
     */
    'target_species'?: PokemonSpecies;
    /**
     * The list of effects that are changed by this ability
     * @type {Array<AbilityEffectChange>}
     * @memberof Effect
     */
    'effect_changes'?: Array<AbilityEffectChange>;
    /**
     * The flavor text entries that describe this effect
     * @type {Array<FlavorText>}
     * @memberof Effect
     */
    'flavor_text_entries'?: Array<FlavorText>;
    /**
     * 
     * @type {Generation}
     * @memberof Effect
     */
    'generation'?: Generation;
    /**
     * The machines that teach this move
     * @type {Array<MachineVersionDetail>}
     * @memberof Effect
     */
    'machines'?: Array<MachineVersionDetail>;
    /**
     * 
     * @type {MoveMetaData}
     * @memberof Effect
     */
    'meta'?: MoveMetaData;
    /**
     * The short description of this effect listed in different languages
     * @type {string}
     * @memberof Effect
     */
    'short_effect'?: string;
    /**
     * The chance of this move having an additional effect listed in percentage
     * @type {number}
     * @memberof Effect
     */
    'effect_chance'?: number;
    /**
     * The list of stat changes that are caused by this effect
     * @type {Array<MoveStatChange>}
     * @memberof Effect
     */
    'stat_changes'?: Array<MoveStatChange>;
    /**
     * 
     * @type {SuperContestEffect}
     * @memberof Effect
     */
    'super_contest_effect'?: SuperContestEffect;
    /**
     * 
     * @type {ContestComboSets}
     * @memberof Effect
     */
    'contest_combos'?: ContestComboSets;
    /**
     * 
     * @type {ContestType}
     * @memberof Effect
     */
    'contest_type'?: ContestType;
}

