/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Name } from './name';
// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * 
 * @export
 * @interface EggGroup
 */
export interface EggGroup {
    /**
     * The identifier for this egg group resource
     * @type {number}
     * @memberof EggGroup
     */
    'id': number;
    /**
     * The name for this egg group resource
     * @type {string}
     * @memberof EggGroup
     */
    'name': string;
    /**
     * The name of this egg group listed in different languages
     * @type {Array<Name>}
     * @memberof EggGroup
     */
    'names': Array<Name>;
    /**
     * A list of all Pokemon species that are members of this egg group
     * @type {Array<NamedAPIResource>}
     * @memberof EggGroup
     */
    'pokemon_species': Array<NamedAPIResource>;
}

