/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Name } from './name';
// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * 
 * @export
 * @interface EncounterConditionValue
 */
export interface EncounterConditionValue {
    /**
     * The identifier for this encounter condition value resource
     * @type {number}
     * @memberof EncounterConditionValue
     */
    'id': number;
    /**
     * The name for this encounter condition value resource
     * @type {string}
     * @memberof EncounterConditionValue
     */
    'name': string;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof EncounterConditionValue
     */
    'condition': NamedAPIResource;
    /**
     * The name of this encounter condition value listed in different languages
     * @type {Array<Name>}
     * @memberof EncounterConditionValue
     */
    'names': Array<Name>;
}

