/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EncounterMethod
 */
export interface EncounterMethod {
    /**
     * The identifier for this encounter method resource
     * @type {number}
     * @memberof EncounterMethod
     */
    'id': number;
    /**
     * The name for this encounter method resource
     * @type {string}
     * @memberof EncounterMethod
     */
    'name': string;
    /**
     * A good value for sorting
     * @type {number}
     * @memberof EncounterMethod
     */
    'order': number;
}

