/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EncounterCondition } from './encounter-condition';

/**
 * 
 * @export
 * @interface EncounterConditionList200Response
 */
export interface EncounterConditionList200Response {
    /**
     * The total number of encounter conditions.
     * @type {number}
     * @memberof EncounterConditionList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of encounter conditions.
     * @type {string}
     * @memberof EncounterConditionList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of encounter conditions.
     * @type {string}
     * @memberof EncounterConditionList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<EncounterCondition>}
     * @memberof EncounterConditionList200Response
     */
    'results'?: Array<EncounterCondition>;
}

