/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Encounter } from './encounter';
// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * Version details of an encounter.
 * @export
 * @interface EncounterVersionDetails
 */
export interface EncounterVersionDetails {
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof EncounterVersionDetails
     */
    'version'?: NamedAPIResource;
    /**
     * The total percentage of all encounter potential.
     * @type {number}
     * @memberof EncounterVersionDetails
     */
    'max_chance'?: number;
    /**
     * A list of encounters and their specifics.
     * @type {Array<Encounter>}
     * @memberof EncounterVersionDetails
     */
    'encounter_details'?: Array<Encounter>;
}

