/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EvolutionChainBabyTriggerItem } from './evolution-chain-baby-trigger-item';
// May contain unused imports in some cases
// @ts-ignore
import { EvolutionChainChain } from './evolution-chain-chain';

/**
 * 
 * @export
 * @interface EvolutionChain
 */
export interface EvolutionChain {
    /**
     * The identifier for this evolution chain resource
     * @type {number}
     * @memberof EvolutionChain
     */
    'id': number;
    /**
     * 
     * @type {EvolutionChainBabyTriggerItem}
     * @memberof EvolutionChain
     */
    'baby_trigger_item'?: EvolutionChainBabyTriggerItem | null;
    /**
     * 
     * @type {EvolutionChainChain}
     * @memberof EvolutionChain
     */
    'chain': EvolutionChainChain;
}

