/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbilityEffectChange } from './ability-effect-change';
// May contain unused imports in some cases
// @ts-ignore
import { ContestComboSets } from './contest-combo-sets';
// May contain unused imports in some cases
// @ts-ignore
import { Move } from './move';
// May contain unused imports in some cases
// @ts-ignore
import { MoveContestEffect } from './move-contest-effect';
// May contain unused imports in some cases
// @ts-ignore
import { MoveContestType } from './move-contest-type';
// May contain unused imports in some cases
// @ts-ignore
import { MoveMetaData } from './move-meta-data';
// May contain unused imports in some cases
// @ts-ignore
import { MoveStatChange } from './move-stat-change';
// May contain unused imports in some cases
// @ts-ignore
import { Name } from './name';
// May contain unused imports in some cases
// @ts-ignore
import { PastMoveStatValues } from './past-move-stat-values';
// May contain unused imports in some cases
// @ts-ignore
import { VerboseEffect } from './verbose-effect';

/**
 * @type EvolutionChainChainEvolutionDetailsInnerKnownMove
 * @export
 */
export type EvolutionChainChainEvolutionDetailsInnerKnownMove = Move | any;


