/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GenderPokemonSpeciesDetailsInner
 */
export interface GenderPokemonSpeciesDetailsInner {
    /**
     * The chance of this Pokémon being female, in eighths; or -1 for genderless
     * @type {number}
     * @memberof GenderPokemonSpeciesDetailsInner
     */
    'rate'?: number;
}

