/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GenerationAbilitiesInner } from './generation-abilities-inner';
// May contain unused imports in some cases
// @ts-ignore
import { GenerationNamesInner } from './generation-names-inner';

/**
 * 
 * @export
 * @interface Generation
 */
export interface Generation {
    /**
     * The identifier for this generation resource
     * @type {number}
     * @memberof Generation
     */
    'id'?: number;
    /**
     * The name for this generation resource
     * @type {string}
     * @memberof Generation
     */
    'name'?: string;
    /**
     * 
     * @type {Array<GenerationAbilitiesInner>}
     * @memberof Generation
     */
    'abilities'?: Array<GenerationAbilitiesInner>;
    /**
     * 
     * @type {Array<GenerationNamesInner>}
     * @memberof Generation
     */
    'names'?: Array<GenerationNamesInner>;
}

