/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GenerationAbilitiesInner
 */
export interface GenerationAbilitiesInner {
    /**
     * The name of this ability
     * @type {string}
     * @memberof GenerationAbilitiesInner
     */
    'name'?: string;
    /**
     * Whether or not this ability is a hidden one
     * @type {boolean}
     * @memberof GenerationAbilitiesInner
     */
    'is_hidden'?: boolean;
    /**
     * The slot this ability occupies in this Pokémon species
     * @type {number}
     * @memberof GenerationAbilitiesInner
     */
    'slot'?: number;
}

