/* tslint:disable */
/* eslint-disable */
/**
 * KG Pokemon API
 * Pokemon API for Konrad developer onboarding.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PokemonTypes } from './pokemon-types';

/**
 * 
 * @export
 * @interface GetTypes200ResponseInner
 */
export interface GetTypes200ResponseInner {
    /**
     * 
     * @type {PokemonTypes}
     * @memberof GetTypes200ResponseInner
     */
    'name'?: PokemonTypes;
    /**
     * 
     * @type {Array<PokemonTypes>}
     * @memberof GetTypes200ResponseInner
     */
    'weaknesses'?: Array<PokemonTypes>;
    /**
     * 
     * @type {Array<PokemonTypes>}
     * @memberof GetTypes200ResponseInner
     */
    'strengths'?: Array<PokemonTypes>;
}



