/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GrowthRate } from './growth-rate';

/**
 * 
 * @export
 * @interface GrowthRateList200Response
 */
export interface GrowthRateList200Response {
    /**
     * The total number of growth rates.
     * @type {number}
     * @memberof GrowthRateList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of growth rates.
     * @type {string}
     * @memberof GrowthRateList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of growth rates.
     * @type {string}
     * @memberof GrowthRateList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<GrowthRate>}
     * @memberof GrowthRateList200Response
     */
    'results'?: Array<GrowthRate>;
}

