/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Item } from './item';

/**
 * 
 * @export
 * @interface ItemList200Response
 */
export interface ItemList200Response {
    /**
     * The total number of items.
     * @type {number}
     * @memberof ItemList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of items.
     * @type {string}
     * @memberof ItemList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of items.
     * @type {string}
     * @memberof ItemList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<Item>}
     * @memberof ItemList200Response
     */
    'results'?: Array<Item>;
}

