/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GenerationGameIndex } from './generation-game-index';
// May contain unused imports in some cases
// @ts-ignore
import { Name } from './name';
// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'name'?: string;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof Location
     */
    'region'?: NamedAPIResource;
    /**
     * 
     * @type {Array<Name>}
     * @memberof Location
     */
    'names'?: Array<Name>;
    /**
     * 
     * @type {Array<GenerationGameIndex>}
     * @memberof Location
     */
    'game_indices'?: Array<GenerationGameIndex>;
    /**
     * 
     * @type {Array<NamedAPIResource>}
     * @memberof Location
     */
    'areas'?: Array<NamedAPIResource>;
}

