/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Machine } from './machine';

/**
 * 
 * @export
 * @interface MachineList200Response
 */
export interface MachineList200Response {
    /**
     * The total number of machines.
     * @type {number}
     * @memberof MachineList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of machines.
     * @type {string}
     * @memberof MachineList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of machines.
     * @type {string}
     * @memberof MachineList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<Machine>}
     * @memberof MachineList200Response
     */
    'results'?: Array<Machine>;
}

