/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MoveTarget } from './move-target';

/**
 * 
 * @export
 * @interface MoveTargetList200Response
 */
export interface MoveTargetList200Response {
    /**
     * The total number of move targets.
     * @type {number}
     * @memberof MoveTargetList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of move targets.
     * @type {string}
     * @memberof MoveTargetList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of move targets.
     * @type {string}
     * @memberof MoveTargetList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<MoveTarget>}
     * @memberof MoveTargetList200Response
     */
    'results'?: Array<MoveTarget>;
}

