/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * 
 * @export
 * @interface MoveBattleStylePreference
 */
export interface MoveBattleStylePreference {
    /**
     * Chance of using the move, in percent, if HP is under one half of maximum HP.
     * @type {number}
     * @memberof MoveBattleStylePreference
     */
    'low_hp_preference': number;
    /**
     * Chance of using the move, in percent, if HP is over one half of maximum HP.
     * @type {number}
     * @memberof MoveBattleStylePreference
     */
    'high_hp_preference': number;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof MoveBattleStylePreference
     */
    'move_battle_style': NamedAPIResource;
}

