/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Nature } from './nature';

/**
 * 
 * @export
 * @interface NatureList200Response
 */
export interface NatureList200Response {
    /**
     * The total number of natures.
     * @type {number}
     * @memberof NatureList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of natures.
     * @type {string}
     * @memberof NatureList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of natures.
     * @type {string}
     * @memberof NatureList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<Nature>}
     * @memberof NatureList200Response
     */
    'results'?: Array<Nature>;
}

