/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MoveBattleStylePreference } from './move-battle-style-preference';
// May contain unused imports in some cases
// @ts-ignore
import { NatureStatChange } from './nature-stat-change';

/**
 * 
 * @export
 * @interface Nature
 */
export interface Nature {
    /**
     * 
     * @type {number}
     * @memberof Nature
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Nature
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Nature
     */
    'decreased_stat': string;
    /**
     * 
     * @type {string}
     * @memberof Nature
     */
    'increased_stat': string;
    /**
     * 
     * @type {string}
     * @memberof Nature
     */
    'hates_flavor': string;
    /**
     * 
     * @type {string}
     * @memberof Nature
     */
    'likes_flavor': string;
    /**
     * 
     * @type {Array<NatureStatChange>}
     * @memberof Nature
     */
    'pokeathlon_stat_changes'?: Array<NatureStatChange>;
    /**
     * 
     * @type {Array<MoveBattleStylePreference>}
     * @memberof Nature
     */
    'move_battle_style_preferences'?: Array<MoveBattleStylePreference>;
}

