/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PalParkArea } from './pal-park-area';

/**
 * 
 * @export
 * @interface PalParkAreaList200Response
 */
export interface PalParkAreaList200Response {
    /**
     * The total number of pal park areas.
     * @type {number}
     * @memberof PalParkAreaList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of pal park areas.
     * @type {string}
     * @memberof PalParkAreaList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of pal park areas.
     * @type {string}
     * @memberof PalParkAreaList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<PalParkArea>}
     * @memberof PalParkAreaList200Response
     */
    'results'?: Array<PalParkArea>;
}

