/* tslint:disable */
/* eslint-disable */
/**
 * KG Pokemon API
 * Pokemon API for Konrad developer onboarding.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Pokemon } from './pokemon';

/**
 * Collection of up to 6 owned pokemon
 * @export
 * @interface Party
 */
export interface Party {
    /**
     * Optional party name given by user
     * @type {string}
     * @memberof Party
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Party
     */
    'id'?: string;
    /**
     * 
     * @type {Array<Pokemon>}
     * @memberof Party
     */
    'pokemon'?: Array<Pokemon>;
    /**
     * 
     * @type {string}
     * @memberof Party
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Party
     */
    'modified'?: string;
}

