/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PastMoveStatValuesEffectEntriesInner } from './past-move-stat-values-effect-entries-inner';
// May contain unused imports in some cases
// @ts-ignore
import { Type } from './type';

/**
 * 
 * @export
 * @interface PastMoveStatValues
 */
export interface PastMoveStatValues {
    /**
     * The percent value of how likely this move is to be successful.
     * @type {number}
     * @memberof PastMoveStatValues
     */
    'accuracy': number;
    /**
     * The percent value of effect occurring.
     * @type {number}
     * @memberof PastMoveStatValues
     */
    'effect_chance'?: number;
    /**
     * The base power of this move with a value of 0 if it does not have a base power.
     * @type {number}
     * @memberof PastMoveStatValues
     */
    'power': number;
    /**
     * The power points this move has left.
     * @type {number}
     * @memberof PastMoveStatValues
     */
    'pp': number;
    /**
     * The list of previous effects this move has had across version groups.
     * @type {Array<PastMoveStatValuesEffectEntriesInner>}
     * @memberof PastMoveStatValues
     */
    'effect_entries'?: Array<PastMoveStatValuesEffectEntriesInner>;
    /**
     * 
     * @type {Type}
     * @memberof PastMoveStatValues
     */
    'type'?: Type;
}

