/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonAbility } from './pokemon-ability';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonForm } from './pokemon-form';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonHeldItem } from './pokemon-held-item';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonMove } from './pokemon-move';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonSprites } from './pokemon-sprites';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonStat } from './pokemon-stat';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonType } from './pokemon-type';
// May contain unused imports in some cases
// @ts-ignore
import { VersionGameIndex } from './version-game-index';

/**
 * 
 * @export
 * @interface Pokemon
 */
export interface Pokemon {
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    'base_experience': number;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    'height': number;
    /**
     * 
     * @type {boolean}
     * @memberof Pokemon
     */
    'is_default': boolean;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    'order': number;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    'weight': number;
    /**
     * 
     * @type {Array<PokemonAbility>}
     * @memberof Pokemon
     */
    'abilities': Array<PokemonAbility>;
    /**
     * 
     * @type {Array<PokemonForm>}
     * @memberof Pokemon
     */
    'forms': Array<PokemonForm>;
    /**
     * 
     * @type {Array<VersionGameIndex>}
     * @memberof Pokemon
     */
    'game_indices': Array<VersionGameIndex>;
    /**
     * 
     * @type {Array<PokemonHeldItem>}
     * @memberof Pokemon
     */
    'held_items': Array<PokemonHeldItem>;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    'location_area_encounters': string;
    /**
     * 
     * @type {Array<PokemonMove>}
     * @memberof Pokemon
     */
    'moves': Array<PokemonMove>;
    /**
     * 
     * @type {PokemonSprites}
     * @memberof Pokemon
     */
    'sprites': PokemonSprites;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof Pokemon
     */
    'species': NamedAPIResource;
    /**
     * 
     * @type {Array<PokemonStat>}
     * @memberof Pokemon
     */
    'stats': Array<PokemonStat>;
    /**
     * 
     * @type {Array<PokemonType>}
     * @memberof Pokemon
     */
    'types': Array<PokemonType>;
}

