/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PokemonShape } from './pokemon-shape';

/**
 * 
 * @export
 * @interface PokemonShapeList200Response
 */
export interface PokemonShapeList200Response {
    /**
     * The total number of pokemon shapes.
     * @type {number}
     * @memberof PokemonShapeList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of pokemon shapes.
     * @type {string}
     * @memberof PokemonShapeList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of pokemon shapes.
     * @type {string}
     * @memberof PokemonShapeList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<PokemonShape>}
     * @memberof PokemonShapeList200Response
     */
    'results'?: Array<PokemonShape>;
}

