/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PokemonSprites
 */
export interface PokemonSprites {
    /**
     * The default depiction of this Pokémon from the front in battle.
     * @type {string}
     * @memberof PokemonSprites
     */
    'front_default'?: string;
    /**
     * The shiny depiction of this Pokémon from the front in battle, for female gendered Pokémon.
     * @type {string}
     * @memberof PokemonSprites
     */
    'front_female'?: string;
    /**
     * The shiny depiction of this Pokémon from the front in battle.
     * @type {string}
     * @memberof PokemonSprites
     */
    'front_shiny'?: string;
    /**
     * The shiny depiction of this Pokémon from the front in battle, for female gendered Pokémon.
     * @type {string}
     * @memberof PokemonSprites
     */
    'front_shiny_female'?: string;
    /**
     * The default depiction of this Pokémon from the back in battle.
     * @type {string}
     * @memberof PokemonSprites
     */
    'back_default'?: string;
    /**
     * The shiny depiction of this Pokémon from the back in battle, for female gendered Pokémon.
     * @type {string}
     * @memberof PokemonSprites
     */
    'back_female'?: string;
    /**
     * The shiny depiction of this Pokémon from the back in battle.
     * @type {string}
     * @memberof PokemonSprites
     */
    'back_shiny'?: string;
    /**
     * The shiny depiction of this Pokémon from the back in battle, for female gendered Pokémon.
     * @type {string}
     * @memberof PokemonSprites
     */
    'back_shiny_female'?: string;
}

