/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PokemonColor } from './pokemon-color';

/**
 * 
 * @export
 * @interface PokemonColorList200Response
 */
export interface PokemonColorList200Response {
    /**
     * The total number of pokemon colors.
     * @type {number}
     * @memberof PokemonColorList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of pokemon colors.
     * @type {string}
     * @memberof PokemonColorList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of pokemon colors.
     * @type {string}
     * @memberof PokemonColorList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<PokemonColor>}
     * @memberof PokemonColorList200Response
     */
    'results'?: Array<PokemonColor>;
}

