/* tslint:disable */
/* eslint-disable */
/**
 * KG Pokemon API
 * Pokemon API for Konrad developer onboarding.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A Pokemon owned by the trainer
 * @export
 * @interface Pokemon
 */
export interface Pokemon {
    /**
     * ID of this Pokemon instance
     * @type {string}
     * @memberof Pokemon
     */
    'id'?: string;
    /**
     * The Pokemon\'s current abilities
     * @type {Array<string>}
     * @memberof Pokemon
     */
    'abilities'?: Array<string>;
    /**
     * Number of the pokemon this is an instance of
     * @type {number}
     * @memberof Pokemon
     */
    'pokemon'?: number;
    /**
     * 
     * @type {number}
     * @memberof Pokemon
     */
    'level'?: number;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    'nickname'?: string;
    /**
     * 
     * @type {string}
     * @memberof Pokemon
     */
    'caught'?: string;
}

