/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NaturePokeathlonStatAffectSets } from './nature-pokeathlon-stat-affect-sets';

/**
 * A detail of natures which affect this Pokéathlon stat positively or negatively
 * @export
 * @interface PokeathlonStatAffectingNatures
 */
export interface PokeathlonStatAffectingNatures {
    /**
     * A list of natures that positively affect this Pokéathlon stat
     * @type {Array<NaturePokeathlonStatAffectSets>}
     * @memberof PokeathlonStatAffectingNatures
     */
    'increase'?: Array<NaturePokeathlonStatAffectSets>;
    /**
     * A list of natures that negatively affect this Pokéathlon stat
     * @type {Array<NaturePokeathlonStatAffectSets>}
     * @memberof PokeathlonStatAffectingNatures
     */
    'decrease'?: Array<NaturePokeathlonStatAffectSets>;
}

