/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Name } from './name';

/**
 * 
 * @export
 * @interface PokeathlonStatName
 */
export interface PokeathlonStatName {
    /**
     * 
     * @type {string}
     * @memberof PokeathlonStatName
     */
    'name'?: string;
    /**
     * 
     * @type {Array<Name>}
     * @memberof PokeathlonStatName
     */
    'names'?: Array<Name>;
}

