/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Pokemon } from './pokemon';

/**
 * 
 * @export
 * @interface PokemonSpeciesVariety
 */
export interface PokemonSpeciesVariety {
    /**
     * Whether this is the default \"natural\" variety of this species. Note that \"default\" is subjective and that it may not match the Pokémon games\' official status. 
     * @type {boolean}
     * @memberof PokemonSpeciesVariety
     */
    'is_default'?: boolean;
    /**
     * 
     * @type {Pokemon}
     * @memberof PokemonSpeciesVariety
     */
    'pokemon'?: Pokemon;
    /**
     * The name of this Pokémon species variety
     * @type {string}
     * @memberof PokemonSpeciesVariety
     */
    'name'?: string;
}

