/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PokemonForm
 */
export interface PokemonForm {
    /**
     * The identifier for this Pokemon form resource
     * @type {number}
     * @memberof PokemonForm
     */
    'id'?: number;
    /**
     * The name for this Pokemon form resource
     * @type {string}
     * @memberof PokemonForm
     */
    'name'?: string;
}

