/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';
// May contain unused imports in some cases
// @ts-ignore
import { PokemonMoveVersionGroupDetailsInner } from './pokemon-move-version-group-details-inner';

/**
 * 
 * @export
 * @interface PokemonMove
 */
export interface PokemonMove {
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonMove
     */
    'move'?: NamedAPIResource;
    /**
     * A list of details showing how the Pokémon can learn the move 
     * @type {Array<PokemonMoveVersionGroupDetailsInner>}
     * @memberof PokemonMove
     */
    'version_group_details'?: Array<PokemonMoveVersionGroupDetailsInner>;
}

