/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EncounterVersionDetails } from './encounter-version-details';
// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * Encounters Pokemon that can be encountered in the game and the version groups in which they can be encountered.
 * @export
 * @interface PokemonEncounter
 */
export interface PokemonEncounter {
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof PokemonEncounter
     */
    'pokemon'?: NamedAPIResource;
    /**
     * 
     * @type {Array<EncounterVersionDetails>}
     * @memberof PokemonEncounter
     */
    'version_details'?: Array<EncounterVersionDetails>;
}

