/* tslint:disable */
/* eslint-disable */
/**
 * KG Pokemon API
 * Pokemon API for Konrad developer onboarding.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PutPartyRequest
 */
export interface PutPartyRequest {
    /**
     * 
     * @type {string}
     * @memberof PutPartyRequest
     */
    'name'?: string;
    /**
     * IDs of pokemon to add to party
     * @type {Array<string>}
     * @memberof PutPartyRequest
     */
    'pokemon': Array<string>;
}

