/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Name } from './name';
// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * 
 * @export
 * @interface Region
 */
export interface Region {
    /**
     * 
     * @type {number}
     * @memberof Region
     */
    'id': number;
    /**
     * 
     * @type {Array<NamedAPIResource>}
     * @memberof Region
     */
    'locations': Array<NamedAPIResource>;
    /**
     * 
     * @type {string}
     * @memberof Region
     */
    'name': string;
    /**
     * 
     * @type {Array<Name>}
     * @memberof Region
     */
    'names': Array<Name>;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof Region
     */
    'main_generation': NamedAPIResource;
    /**
     * 
     * @type {Array<NamedAPIResource>}
     * @memberof Region
     */
    'pokedexes': Array<NamedAPIResource>;
    /**
     * 
     * @type {Array<NamedAPIResource>}
     * @memberof Region
     */
    'version_groups': Array<NamedAPIResource>;
}

