/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MoveStatAffectSets } from './move-stat-affect-sets';
// May contain unused imports in some cases
// @ts-ignore
import { NatureStatAffectSets } from './nature-stat-affect-sets';

/**
 * 
 * @export
 * @interface Stat
 */
export interface Stat {
    /**
     * 
     * @type {number}
     * @memberof Stat
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Stat
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof Stat
     */
    'game_index': number;
    /**
     * 
     * @type {boolean}
     * @memberof Stat
     */
    'is_battle_only'?: boolean;
    /**
     * 
     * @type {MoveStatAffectSets}
     * @memberof Stat
     */
    'affecting_moves'?: MoveStatAffectSets;
    /**
     * 
     * @type {NatureStatAffectSets}
     * @memberof Stat
     */
    'affecting_natures'?: NatureStatAffectSets;
}

