/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Stat } from './stat';

/**
 * 
 * @export
 * @interface StatList200Response
 */
export interface StatList200Response {
    /**
     * The total number of stats.
     * @type {number}
     * @memberof StatList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of stats.
     * @type {string}
     * @memberof StatList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of stats.
     * @type {string}
     * @memberof StatList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<Stat>}
     * @memberof StatList200Response
     */
    'results'?: Array<Stat>;
}

