/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SuperContestEffect } from './super-contest-effect';

/**
 * 
 * @export
 * @interface SuperContestEffectList200Response
 */
export interface SuperContestEffectList200Response {
    /**
     * The total number of super contest effects.
     * @type {number}
     * @memberof SuperContestEffectList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of super contest effects.
     * @type {string}
     * @memberof SuperContestEffectList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of super contest effects.
     * @type {string}
     * @memberof SuperContestEffectList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<SuperContestEffect>}
     * @memberof SuperContestEffectList200Response
     */
    'results'?: Array<SuperContestEffect>;
}

