/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TypeGeneration
 */
export interface TypeGeneration {
    /**
     * The generation this type originated in.
     * @type {string}
     * @memberof TypeGeneration
     */
    'name'?: string;
    /**
     * The URL of the API endpoint for this generation.
     * @type {string}
     * @memberof TypeGeneration
     */
    'url'?: string;
}

