/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TypeDamageRelationsDoubleDamageFromInner } from './type-damage-relations-double-damage-from-inner';

/**
 * 
 * @export
 * @interface TypeDamageRelations
 */
export interface TypeDamageRelations {
    /**
     * 
     * @type {Array<TypeDamageRelationsDoubleDamageFromInner>}
     * @memberof TypeDamageRelations
     */
    'double_damage_from'?: Array<TypeDamageRelationsDoubleDamageFromInner>;
    /**
     * 
     * @type {Array<TypeDamageRelationsDoubleDamageFromInner>}
     * @memberof TypeDamageRelations
     */
    'double_damage_to'?: Array<TypeDamageRelationsDoubleDamageFromInner>;
    /**
     * 
     * @type {Array<TypeDamageRelationsDoubleDamageFromInner>}
     * @memberof TypeDamageRelations
     */
    'half_damage_from'?: Array<TypeDamageRelationsDoubleDamageFromInner>;
    /**
     * 
     * @type {Array<TypeDamageRelationsDoubleDamageFromInner>}
     * @memberof TypeDamageRelations
     */
    'half_damage_to'?: Array<TypeDamageRelationsDoubleDamageFromInner>;
    /**
     * 
     * @type {Array<TypeDamageRelationsDoubleDamageFromInner>}
     * @memberof TypeDamageRelations
     */
    'no_damage_from'?: Array<TypeDamageRelationsDoubleDamageFromInner>;
    /**
     * 
     * @type {Array<TypeDamageRelationsDoubleDamageFromInner>}
     * @memberof TypeDamageRelations
     */
    'no_damage_to'?: Array<TypeDamageRelationsDoubleDamageFromInner>;
}

