/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NamedAPIResource } from './named-apiresource';

/**
 * 
 * @export
 * @interface VersionGroup
 */
export interface VersionGroup {
    /**
     * 
     * @type {number}
     * @memberof VersionGroup
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof VersionGroup
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof VersionGroup
     */
    'order': number;
    /**
     * 
     * @type {NamedAPIResource}
     * @memberof VersionGroup
     */
    'generation': NamedAPIResource;
    /**
     * 
     * @type {Array<NamedAPIResource>}
     * @memberof VersionGroup
     */
    'move_learn_methods': Array<NamedAPIResource>;
    /**
     * 
     * @type {Array<NamedAPIResource>}
     * @memberof VersionGroup
     */
    'pokedexes': Array<NamedAPIResource>;
    /**
     * 
     * @type {Array<NamedAPIResource>}
     * @memberof VersionGroup
     */
    'regions': Array<NamedAPIResource>;
    /**
     * 
     * @type {Array<NamedAPIResource>}
     * @memberof VersionGroup
     */
    'versions': Array<NamedAPIResource>;
}

