/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20220523
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Version } from './version';

/**
 * 
 * @export
 * @interface VersionList200Response
 */
export interface VersionList200Response {
    /**
     * The total number of versions.
     * @type {number}
     * @memberof VersionList200Response
     */
    'count'?: number;
    /**
     * URL to retrieve the next page of versions.
     * @type {string}
     * @memberof VersionList200Response
     */
    'next'?: string | null;
    /**
     * URL to retrieve the previous page of versions.
     * @type {string}
     * @memberof VersionList200Response
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<Version>}
     * @memberof VersionList200Response
     */
    'results'?: Array<Version>;
}

